//! Ports related to test execution and reporting.

use async_trait::async_trait;
use tokio::sync::mpsc::Receiver;

use crate::domain::entities::{MetricsEvent, RetryPolicy, TestResult, TestSpec};
use crate::domain::errors::PulseResult;

/// Runs test specifications and returns their results.
pub trait TestRunnerPort {
    fn run_specs(
        &self,
        specs: &[TestSpec],
        workers: usize,
        retry: RetryPolicy,
    ) -> PulseResult<Vec<TestResult>>;
}

/// Detects file changes that may trigger test runs.
pub trait ChangeDetectorPort {
    fn changed_files(&self) -> PulseResult<Vec<String>>;
}

/// Events generated by the file system watcher.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum WatchEvent {
    Created,
    Modified,
    Removed,
    Other,
}

#[async_trait]
pub trait WatcherPort {
    async fn watch(&self, path: &str) -> PulseResult<Receiver<WatchEvent>>;
}

/// Maps changed files to test specifications.
pub trait RouteIndexerPort {
    fn map_changes_to_specs(&self, changed_files: &[String]) -> PulseResult<Vec<String>>;
}

/// Publishes reports produced by test executions.
pub trait ReportPublisherPort {
    fn publish(&self) -> PulseResult<()>;
}

/// Sink for emitting metrics events.
pub trait MetricsSinkPort {
    fn emit(&self, event: MetricsEvent);
}

