// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SIMULATOR`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `initialize`

Future<void> startSimulator({
  required String servicesDir,
  required String dbPath,
}) => RustLib.instance.api.crateApiStartSimulator(
  servicesDir: servicesDir,
  dbPath: dbPath,
);

Future<void> stopSimulator() => RustLib.instance.api.crateApiStopSimulator();

Future<List<ServiceStatus>> getActiveServices() =>
    RustLib.instance.api.crateApiGetActiveServices();

Future<String> generateServiceAi({
  required String apiKey,
  required String prompt,
  required String model,
}) => RustLib.instance.api.crateApiGenerateServiceAi(
  apiKey: apiKey,
  prompt: prompt,
  model: model,
);

Future<void> saveServiceDefinition({
  required String path,
  required String content,
}) => RustLib.instance.api.crateApiSaveServiceDefinition(
  path: path,
  content: content,
);

Stream<String> createLogStream() =>
    RustLib.instance.api.crateApiCreateLogStream();

class ServiceStatus {
  final String name;
  final int port;
  final bool isActive;

  const ServiceStatus({
    required this.name,
    required this.port,
    required this.isActive,
  });

  @override
  int get hashCode => name.hashCode ^ port.hashCode ^ isActive.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ServiceStatus &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          port == other.port &&
          isActive == other.isActive;
}
